import { defineStore } from 'pinia'
import { ref } from 'vue'
import { setUsersData } from '../utils/demoIdentities'

export interface DemoUser {
  address: string
  name: string
}

export const useAuthStore = defineStore('auth', () => {
  const user = ref<DemoUser | null>(null)
  const isLoaded = ref(false)
  const hasSetupError = ref(false)

  const loadDemoUser = async () => {
    try {
      // Fetch universally from the clean consolidated users.json file generated by the seeder pipeline
      const response = await fetch('/src/data/users.json')
      
      if (!response.ok) {
        hasSetupError.value = true
        return
      }

      const data = await response.json()
      setUsersData(data)
      
      // Look for the user explicitly tagged by the seeder
      for (const [address, meta] of Object.entries(data)) {
         const m = meta as { name: string, isDemoUser: boolean }
         if (m.isDemoUser) {
           user.value = {
             address,
             name: m.name
           }
           break
         }
      }

      if (!user.value) {
        hasSetupError.value = true
      }
    } catch (e) {
      console.warn("Could not load users.json. Did you run `npm run seed` in the backend?")
      hasSetupError.value = true
    } finally {
      isLoaded.value = true
    }
  }

  return {
    user,
    isLoaded,
    hasSetupError,
    loadDemoUser
  }
})
